#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "common.h"
#include "option.h"

Config config = {
    .fileName = NULL,
    .quiet = false,
    .compileOnly = false,
    .maxHeapSize = 1024 * 1024 * 1024,
    .maxNurserySizePercent = 60,
    .minNurserySizePercent = 5,
};

static void helpAction(Option option, const char* arg);
static void versionAction(Option option, const char* arg);
static void quietAction(Option option, const char* arg);
static void compileOnlyAction(Option option, const char* arg);
static void maxHeapSizeAction(Option option, const char* arg);
static void maxNurserySizePercentAction(Option option, const char* arg);
static void minNurserySizePercentAction(Option option, const char* arg);

Option optionList[] = {
    {"help",                   4, 'h', helpAction,                  NULL},
    {"version",                7, 'V', versionAction,               VERSION_NUMBER},
    {"quiet",                  5, 'q', quietAction,                 "Don't print version number on iteractive shell"},
    {"compileOnly",           11,  0,  compileOnlyAction,           "Prints the generated bytecode to stdout and exit without executing"},
    {"maxHeapSize",           11,  0,  maxHeapSizeAction,           "Sets the maximum heap size"},
    {"maxNurserySizePercent", 21,  0,  maxNurserySizePercentAction, "Maximum nursery size relative to the maximum heap size"},
    {"minNurserySizePercent", 21,  0,  minNurserySizePercentAction, "Minimum nursery size relative to the maximum heap size"},
    {NULL, 0, 0, NULL, NULL}
};

static void missingValueError() {
    fprintf(stderr, "Missing value\n");
    exit(-2);
}

static void invalidValueError(int value) {
    fprintf(stderr, "Invalid value %d\n", value);
    exit(-3);
}

static void helpAction(Option option, const char* arg) {
    printf("zlox version %s\n", optionList[1].description);
    puts("\nOPTIONS\n");
    for (int i = 2; optionList[i].longName; i++) {
        Option option = optionList[i];

        printf("  --%s", option.longName);
        if (option.shortName != 0) printf(" -%c", option.shortName);
        printf("\n      %s\n", option.description);
        putchar('\n');
    }

    exit(0);
}

static void versionAction(Option option, const char* arg) {
    printf("zlox version %s\n", VERSION_NUMBER);
    exit(0);
}

static void quietAction(Option option, const char* arg) {
    config.quiet = true;
}

static void compileOnlyAction(Option option, const char* arg) {
    config.compileOnly = true;
}

static void maxHeapSizeAction(Option option, const char* arg) {
    if (arg[option.length] != '=')
        missingValueError();

    config.maxHeapSize = strtoul(arg + option.length + 1, NULL, 10);
}

static void maxNurserySizePercentAction(Option option, const char* arg) {
    if (arg[option.length] != '=')
        missingValueError();

    int percent = strtol(arg + option.length + 1, NULL, 10);
    if (percent < 0 || percent > 100)
        invalidValueError(percent);
    
    config.maxNurserySizePercent = percent;
}

static void minNurserySizePercentAction(Option option, const char* arg) {
    if (arg[option.length] != '=')
        missingValueError();


    int percent = strtol(arg + option.length + 1, NULL, 10);
    if (percent < 0 || percent > 100)
        invalidValueError(percent);
    
    config.minNurserySizePercent = percent;
}

static int findArg(bool useLongName, const char* name) {
    for (int i = 0; optionList[i].longName != NULL; i++) {
        Option option = optionList[i];

        if ((useLongName && strncmp(option.longName, name, option.length) == 0) || option.shortName == name[0]) {
            return i;
        }
    }

    return -1;
}

static void parseArg(bool useLongName, const char* name) {
    int index = findArg(useLongName, name);
    if (index == -1) {
        fprintf(stderr, "Invalid option %s\n", name);
        exit(-1);
    }

    Option option = optionList[index];
    if (option.action != NULL) {
        option.action(option, name);
    }
}

void parseArgs(int argc, const char* argv[]) {
    for (int i = 1; i < argc; i++) {
        const char* arg = argv[i];
        if (arg[0] == '-') {
            bool useLongName = arg[1] == '-';
            const char* name = &arg[1 + useLongName];
            parseArg(useLongName, name);
        }
        else if (i != argc - 1) {
            fprintf(stderr, "File name must be the last option\n");
            exit(-1);
        }
        else {
            config.fileName = arg;
        }
    }
}
